Rework build-all.sh
KallistiOS/kos-ports pull request #65
Opened 2024-05-02 15:10 UTC by andressbarajas

Try and build everything first and then display errors at the end.

2024-05-02 19:13 UTC, gyrovorbis approved these changes
Thank god, this was much needed... Going to wait to check this in, though, because as much as it LOOKS right to me, I am absolute shit at bash scripting... lol.

2024-05-08 20:06 UTC, darcagn requested changes
Looks good, just a couple suggestions 😄

2024-05-08 20:06 UTC, darcagn commented on utils/build-all.sh
>  for _dir in ${KOS_PORTS}/* ; do
```suggestion
for _dir in $(realpath ${KOS_PORTS})/* ; do
```

If you don't mind, I'd like to suggest here to use `realpath` (POSIX compliant) to make the output look better. For example, before:

```
/opt/toolchains/dc/kos/../kos-ports/cglm: Build failed with return code 2
/opt/toolchains/dc/kos/../kos-ports/libchipmunk: Build failed with return code 2
/opt/toolchains/dc/kos/../kos-ports/libcmark: Build failed with return code 2
/opt/toolchains/dc/kos/../kos-ports/mruby: Build failed with return code 2
```

After:

```
/opt/toolchains/dc/kos-ports/cglm: Build failed with return code 2
/opt/toolchains/dc/kos-ports/libchipmunk: Build failed with return code 2
/opt/toolchains/dc/kos-ports/libcmark: Build failed with return code 2
/opt/toolchains/dc/kos-ports/mruby: Build failed with return code 2
```

This also makes things prettier throughout the rest of the script's text, too.

2024-05-08 20:06 UTC, darcagn commented on utils/build-all.sh
> +    echo "$error_count Error(s) occurred during the build process:"
```suggestion
    echo "$error_count error(s) occurred during the build process:"
```

2024-05-08 20:11 UTC, darcagn approved these changes

2024-05-08 20:12 UTC, merged

2024-05-08 21:36 UTC, QuzarDC reviewed
Looks great! Thanks for that (and noticing the header filename drift, can't believe that was there so long).